version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
    - nlreturn
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    # presets:
      #- comments
      #- common-false-positives
      #- legacy
      #- std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
