version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
    - nlreturn
    - noinlineerr
    - paralleltest
    - wsl
    - wsl_v5
  settings:
    gosec:
      excludes:
        - G115
    wrapcheck:
      extra-ignore-sigs:
        - os.UserConfigDir
  exclusions:
    generated: lax
    # presets:
      #- comments
      #- common-false-positives
      #- legacy
      #- std-error-handling
formatters:
  enable:
    - gofumpt
    - golines
  exclusions:
    generated: lax
