name: Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Build
        run: |
          cd example
          go build -v  .
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: run tests
        run: |
          go vet ./...
          go test ./... -v
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name:  lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
